import fs from 'fs';
import { execSync } from 'child_process';

/**
 * Validates and safely applies code fix to target file.
 * 
 * @param {string} absoluteFilePath Path to source file
 * @param {string} fixedCode Complete code content generated by AI
 * @returns {object} Status of patch operation
 */
export function applyCodePatch(absoluteFilePath, fixedCode) {
  if (!fs.existsSync(absoluteFilePath)) {
    throw new Error(`Cannot patch non-existent file: ${absoluteFilePath}`);
  }

  const backupPath = `${absoluteFilePath}.bak`;

  try {
    // 1. Create backup of original buggy file
    fs.copyFileSync(absoluteFilePath, backupPath);

    // 2. Write new fixed code
    fs.writeFileSync(absoluteFilePath, fixedCode, 'utf8');

    // 3. Perform JS Syntax Validation check
    try {
      execSync(`node --check "${absoluteFilePath}"`, { stdio: 'pipe' });
    } catch (syntaxErr) {
      // Revert backup if syntax check fails
      fs.copyFileSync(backupPath, absoluteFilePath);
      fs.unlinkSync(backupPath);
      throw new Error(`AI generated invalid JavaScript syntax: ${syntaxErr.message}`);
    }

    // 4. Remove backup file upon clean validation
    if (fs.existsSync(backupPath)) {
      fs.unlinkSync(backupPath);
    }

    return {
      success: true,
      filePath: absoluteFilePath,
      message: 'Code patch applied and verified successfully'
    };
  } catch (err) {
    if (fs.existsSync(backupPath)) {
      fs.copyFileSync(backupPath, absoluteFilePath);
      fs.unlinkSync(backupPath);
    }
    throw err;
  }
}
